### PR TITLE
update everything to apps/v1/Deployment

### PR DESCRIPTION
**Pull request by MHBauer**

### CODE REVIEW

**Comment by MHBauer** [comment]
resolves #8

**Comment by duglin** [comment]
When I try to deploy these I get these errors:
```
unable to recognize "guestbook-deployment.yaml": no matches for kind "Deployment" in version "apps/v1"
unable to recognize "redis-master-deployment.yaml": no matches for kind "Deployment" in version "apps/v1"
unable to recognize "redis-slave-deployment.yaml": no matches for kind "Deployment" in version "apps/v1"
```

**Comment by duglin** [comment]
perhaps for bx it needs to be "extensions/v1beta1" until the next upgrade

**Comment by duglin** [comment]
Just tried "extensions/v1beta1" for BX and latest kube and it seems to work. We should use that for now until BX upgrades.

**Comment by cmluciano** [comment]
Yes I think that was in 1.9 that the server made the change. I'm +1 on using the apps/v1 since it works in the 1.9 version of the container service

**Comment by duglin** [comment]
but today's bx isn't on 1.9 so we can't use that yet

**Comment by cmluciano** [comment]
By today's do you mean the default?

**Comment by duglin** [comment]
yes

**Comment by cmluciano** [comment]
Ok. I'll probably just create a 1.9 branch for future usage since I require 1.9 for istio101.

**Comment by MHBauer** [comment]
bx has 1.9 available.

**Pull request merged**
