### PR TITLE
Adding endpoints /healthz and /hello for workshop Lab2.

### PR DESCRIPTION
**Pull request by brahmaroutu**

### CODE REVIEW

**Comment by MHBauer** [comment]
LGTM

**Comment by MHBauer** [comment]
@duglin @jkomg how do I get perms to merge this? How do we officially redeploy to container registry or dockerhub?

**Comment by MHBauer** [comment]
Since this is merged, how do we get fresh images made? Pushed to ibmcom in dockerhub or somewhere else accessible. @duglin

**Comment by duglin** [comment]
I can do it - gimme a few...

**Pull request merged**
