### PR TITLE
This is an attempt to get master/slave out of our vocabulary

### PR DESCRIPTION
**Pull request by jjasghar**
- Leader follower is a positive naming of the status of the
  containers.

This is just a start to a PR I'd love to see some more feedback. :metal:

### CODE REVIEW

**Comment by duglin** [comment]
the redis docs talk about master/slave though - and I'd rather be consistent with those to not confuse people

**Comment by nibalizer** [comment]
Lets do it, our audience is going to be smart people who can handle it

**Comment by jkomg** [comment]
I also approve!

**Comment by duglin** [comment]
its not that simple since this will impact all other workshops we have.

Additionally, if people are smart enough "to handle it" then they're smart enough to know these are well established computer science terms and if you want to change it then start with redis itself.

**Comment by jjasghar** [comment]
Specifically redis has been resistant to this change: https://www.theregister.co.uk/2018/09/13/redis_master_slave/

If we want the change we have to start changing our vocabulary.

**Pull request closed without merging**
