### PR TITLE
update code to use apikey

### PR DESCRIPTION
**Pull request by dcberg**
Changed app.py and deployment yaml to use IBM Cloud apikey to authenticate.

### CODE REVIEW

**Comment by duglin** [comment]
@dcberg can you modify the Makefile so the version string is v1.1 - for both v2 and v1 dirs?

**Comment by linsun** [comment]
@duglin is it just the guestbook/v2/analyzer/Makefile?

**Comment by duglin** [comment]
ah sorry - for some reason I thought the code being touched was in guestbook itself. Yes I think its just the v2/analyzer/Makefile

**Comment by duglin** [comment]
btw - I'm going to add a top-level Makefile that will build and push all lower-level images - kind of annoying having to `cd` around and do each individually

**Comment by linsun** [comment]
merging as Doug has created the top level file now :)

**Comment by duglin** [comment]
@linsun we still need the edits to the analyzer Makefile since the top-level Makefile just calls the lower-level one.

**Pull request merged**
